//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Address.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressList
    {
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string PostalCode { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
    }
}
